PAST_COLS = [
    "clinker_1_feedrate",
    "clinker_2_feedrate",
    "ashes_feedrate",
    "iron_sulfate",
    "glycol",
    "water",
    "mill_output_temp",
    "mill_input_temp",
    "output_vacuum",
    "elevator_1_load",
    "deduster_vacuum",
    "separator_load",
    "separator_output_temp",
    "separator_input_temp",
    "filter_fan_speed",
    "auger_5_load",
    "gran1_obscuration",
    "gran1_dv_10",
    "gran1_dv_50",
    "gran1_dv_90",
    "gran1_vol_gt_100_um",
    "gran1_vol_gt_50_um",
    "gran1_vol_lt_32_um",
    "gran1_vol_in_5_50_um",
    "gran1_cv",
    "gran1_davg_vol",
    "gran1_davg_surf",
    "gran1_vol_lt_5_um",
    "gran2_obscuration",
    "gran2_dv_10",
    "gran2_dv_50",
    "gran2_dv_90",
    "gran2_vol_gt_100_um",
    "gran2_vol_gt_50_um",
    "gran2_vol_lt_32_um",
    "gran2_vol_in_5_50_um",
    "gran2_cv",
    "gran2_blain",
    "gran2_davg_vol",
    "gran2_davg_surf",
    "gran2_vol_lt_5_um",
    "mill_motor_power",
    "filter_power",
    "utility_devices_power",
    "output_devices_power",
    "separator_power",
    "circulation_fan_power",
]

# PAST_COLS = [
#     "stone_slag_feedrate",
#     "glycol",
#     "water",
#     "mill_output_temp",
#     "separator_output_temp",
#     "input_sum",
#     "gran1_obscuration",
#     "gran1_dv_10",
#     "gran1_dv_90",
#     "gran1_vol_gt_100_um",
#     "gran1_davg_vol",
#     "gran1_davg_surf",
#     "gran1_vol_lt_5_um",
#     "gran2_blain",
#     "separator_power"
# ]



INPUT_COLS = [
    # "fresh_feed",
    "input_sum",
    "stone_slag_feedrate",
    "aspiration_fan_speed",
    "gypsum_feedrate",
    "circulation_fan_speed",
    "fresh_air_flap_position",
    "separator_speed"
]

TARGET_COLS = [
    "return",
    "first_chamber_filling",
    "second_chamber_filling",
    "gran1_blain",
]



TIME_COL = "sequence_index"
DEFAULT_FREQ = '1'

SESSION_COL = "session_index"

RAW_COLS = [
    "time",
    "sequence_index",
    "session_index",
    "cement_id",
    "clinker_1_feedrate",
    "clinker_1_feedrate_setpoint",
    "clinker_2_feedrate",
    "clinker_2_feedrate_setpoint",
    "stone_slag_feedrate",
    "stone_slag_feedrate_setpoint",
    "gypsum_feedrate",
    "gypsum_feedrate_setpoint",
    "ashes_feedrate",
    "iron_sulfate",
    "glycol",
    "water",
    "water_setpoint",
    "mill_output_temp",
    "mill_output_temp_setpoint",
    "mill_input_temp",
    "output_vacuum",
    "output_gas_flow",
    "first_chamber_filling",
    "second_chamber_filling",
    "elevator_1_load",
    "deduster_vacuum",
    "separator_load",
    "separator_speed",
    "separator_speed_setpoint",
    "separator_output_temp",
    "separator_input_temp",
    "input_sum",
    "fresh_feed_setpoint",
    "return",
    "circulation_fan_speed",
    "circulation_fan_speed_setpoint",
    "filter_fan_speed",
    "filter_fan_speed_setpoint",
    "aspiration_fan_speed",
    "aspiration_fan_speed_setpoint",
    "fresh_air_flap_position",
    "fresh_air_flap_position_setpoint",
    "auger_5_load",
    "gran1_obscuration",
    "gran1_dv_10",
    "gran1_dv_50",
    "gran1_dv_90",
    "gran1_vol_gt_100_um",
    "gran1_vol_gt_50_um",
    "gran1_vol_lt_32_um",
    "gran1_vol_in_5_50_um",
    "gran1_cv",
    "gran1_blain",
    "gran1_davg_vol",
    "gran1_davg_surf",
    "gran1_vol_lt_5_um",
    "gran2_obscuration",
    "gran2_dv_10",
    "gran2_dv_50",
    "gran2_dv_90",
    "gran2_vol_gt_100_um",
    "gran2_vol_gt_50_um",
    "gran2_vol_lt_32_um",
    "gran2_vol_in_5_50_um",
    "gran2_cv",
    "gran2_blain",
    "gran2_davg_vol",
    "gran2_davg_surf",
    "gran2_vol_lt_5_um",
    "mill_motor_power",
    "filter_power",
    "utility_devices_power",
    "output_devices_power",
    "separator_power",
    "circulation_fan_power",
]
